import nodemailer from 'nodemailer';

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ message: 'Method not allowed' });
  }

  const { tableData, recipient } = req.body;

  const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_PASS,
    },
  });

  const tableRows = tableData
    .map(
      (item) => `
      <tr>
        <td style="padding: 12px 16px; border-bottom: 1px solid #e0e7ff; color: #1a1a2e;">${item.name}</td>
        <td style="padding: 12px 16px; border-bottom: 1px solid #e0e7ff; color: #1a1a2e;">${item.association}</td>
        <td style="padding: 12px 16px; border-bottom: 1px solid #e0e7ff; color: #1a1a2e;">${item.recommendation}</td>
        <td style="padding: 12px 16px; border-bottom: 1px solid #e0e7ff; color: #1a1a2e; text-align: center; font-weight: bold;">${item.lvl}</td>
      </tr>
    `
    )
    .join("");

  const html = `
    <!DOCTYPE html>
    <html>
      <body style="margin: 0; padding: 0; background-color: #ffffff; font-family: system-ui, -apple-system, sans-serif;">
        <div style="width: 100%; background-color: #ffffff;">
          
          <div style="background: linear-gradient(135deg, #1976d2, #42a5f5); padding: 32px; text-align: center;">
            <h1 style="margin: 0; color: #ffffff; font-size: 24px; font-weight: 700; letter-spacing: 0.5px;">
              Observation Report
            </h1>
            <p style="margin: 8px 0 0; color: rgba(255,255,255,0.85); font-size: 14px;">
              Generated by Observation Mailer
            </p>
          </div>

          <div style="padding: 24px; overflow-x: auto;">
            <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
              <thead>
                <tr style="background-color: #e3f2fd;">
                  <th style="padding: 12px 16px; text-align: left; color: #1565c0; font-weight: 600; border-bottom: 2px solid #1976d2;">Observation</th>
                  <th style="padding: 12px 16px; text-align: left; color: #1565c0; font-weight: 600; border-bottom: 2px solid #1976d2;">Association</th>
                  <th style="padding: 12px 16px; text-align: left; color: #1565c0; font-weight: 600; border-bottom: 2px solid #1976d2;">Recommendation</th>
                  <th style="padding: 12px 16px; text-align: center; color: #1565c0; font-weight: 600; border-bottom: 2px solid #1976d2;">Level</th>
                </tr>
              </thead>
              <tbody>
                ${tableRows}
              </tbody>
            </table>
          </div>

          <div style="background-color: #f8faff; padding: 20px 24px; text-align: center; border-top: 1px solid #e0e7ff;">
            <p style="margin: 0; color: #94a3b8; font-size: 12px;">
              This report was generated automatically. Please consult a qualified practitioner before acting on any recommendations.
            </p>
          </div>

        </div>
      </body>
    </html>
  `;

  try {
    await transporter.sendMail({
      from: process.env.EMAIL_USER,
      to: recipient,
      subject: 'Observation Report',
      html,
    });

    res.status(200).json({ message: 'Email sent successfully' });
  } catch (error) {
    res.status(500).json({ message: 'Email failed', error: error.message });
  }
}