export const obsArr = [
  {
    id: 1,
    name: "Haemachromic cells",
    association: "Low energy, fatigue, cellular oxygenation issues, can be connected to haemoglobin levels and coeliac disease.",
    recommendation: "Iron Bisglycinate, B12, Folate, B3, B5, B6, Mag/Potassium. Consider IV B-vitamins.",
  },
  {
    id: 2,
    name: "Chylomicrons (delayed clearing)",
    association: "Gastrointestinal pain (esp. right side), headaches, nausea, low moods, hormonal imbalances, bilious issues.",
    recommendation: "Lecithin, Lipase Digestive Enzymes about 30 minutes after meal, Artichoke Leaf Extract, Milk Thistle.",
  },
  {
    id: 3,
    name: "Chylomicrons (delayed onset)",
    association: "Digestive impairment, liver dysfunction.",
    recommendation: "Lipase Digestive Enzymes (Solgar Advanced), Artichoke Leaf Extract, Milk Thistle.",
  },
  {
    id: 4,
    name: "Platelet aggregation",
    association: "'B' & 'C' sizing can indicate stress conditions or hyperadrenal activity and/or an increase in cardiovascular risk.",
    recommendation: "Stress Formula, B-Complex, Pantothenic Acid (B5).",
  },
  {
    id: 5,
    name: "Hypersecretory platelet aggregation",
    association: "Leaky gut syndrome is the number one associated connection. Inflammation of membranes. High stress load.",
    recommendation: "Spore Probiotic, L-Glutamine, Aloe Vera, Vitamin E, Rhodiola, Pantothenic Acid (B5).",
  },
  {
    id: 6,
    name: "Fibrin clusters",
    association: "Inflammation, intestinal permeability.",
    recommendation: "Spore Probiotic, L-Glutamine, Aloe Vera, Turmeric/Curcumin, Nattokinase, Bromelain, NAC, Pine.",
  },
  {
    id: 7,
    name: "Diffuse fibrin spicules",
    association: "Inflammation, liver function.",
    recommendation: "B-Complex, Glutathione, Selenium, Vitamin E, Resveratrol, Astaxanthin, Curcumin, Nattokinase, Bromelain, NAC, Pycnogenol.",
  },
  {
    id: 8,
    name: "Fibrinogen (balloon on string)",
    association: "Mild inflammation.",
    recommendation: "B-Complex, Curcumin, Multi Vitamin, Vitamin C (higher dose).",
  },
  {
    id: 9,
    name: "Protein linkage",
    association: "Mild inflammation (can indicate previous rouleaux), protein digestion impairment.",
    recommendation: "Multi Nutrient, Spirulina, Greens supplement, Colloidal Minerals, Digestive Enzymes.",
  },
  {
    id: 10,
    name: "Rouleaux (stack of coins)",
    association: "Moderate to high levels of inflammation. Can be directly connected to pre-disease states.",
    recommendation: "High Potency Multi Nutrient, Spirulina, Curcumin/anti-inflam formula, High dose Vitamin C.",
  },
  {
    id: 11,
    name: "Sticky blood (sludge appearance)",
    association: "Malnutritive state, degenerative/pathological indication.",
    recommendation: "Digestive Enzymes (Protease) on an empty stomach, High Potency Multi Nutrient, Advanced Antioxidant Formula.",
  },
  {
    id: 12,
    name: "Haemolysis (ghost cells)",
    association: "Dysbiosis, chemical trauma, infection, immune disorder, oxidative stress on lipid bilayer.",
    recommendation: "High Dose Vitamin C, N-Acetylcysteine (NAC), Glutathione, Vitamin E, Pantothenic Acid (B5).",
  },
  {
    id: 13,
    name: "Anisocytosis (unequal sizing)",
    association: "Diminished cellular oxygen transport, liver dysfunction, altered energy levels.",
    recommendation: "B-Complex, Vitamin C, B12/Methylcobalamin, Folate, Niacin/NMN (NAD+).",
  },
  {
    id: 14,
    name: "Microcytes (<6 microns)",
    association: "Malnutritive state, digestive impairment, chronic blood loss (menstrual), chronic inflammation, heavy metal toxicity, chronic fatigue, anaemic conditions.",
    recommendation: "High Potency Multi Nutrient, Vitamin B12/Methylcobalamin, Folate, Spirulina, Curcumin/anti-inflam formula, High dose Vitamin C, Vitamin A.",
  },
  {
    id: 15,
    name: "Macrocytes (>9 microns)",
    association: "Impaired cellular oxygen transport, shortness of breath, low moods, low energy, chronic headaches, peripheral nerve pain, methylation imbalance.",
    recommendation: "Vitamin B12/Methylcobalamin + Folate + B-Complex. Recommend DNA Health Panel to determine methylation levels.",
  },
  {
    id: 16,
    name: "Elliptocyte (ovalocyte)",
    association: "Can indicate the presence of a hormonal imbalance, megaloblastic anaemia state.",
    recommendation: "Pyridoxal-5'-Phosphate (P5P/Act. B6), Zinc, Vitamin B12/Methylcobalamin, Folate, B-Complex, Hormonal Support Formula.",
  },
  {
    id: 17,
    name: "Neutrophils — band cells (C or S shaped nucleus)",
    association: "Bacterial infection, viral infection, chronic stress.",
    recommendation: "Wild Oregano Oil, Probiotic, Stress Formula, Vitamin B12/Methylcobalamin, Folate, Anti-Bacterial Herbal Formula.",
  },
  {
    id: 18,
    name: "Neutrophils — myelocytes",
    association: "Bacterial infection, acute inflammation, connected to tissue damage (infarction), low moods/energy.",
    recommendation: "Wild Oregano Oil, Probiotic, Vitamin E, Vitamin A, Vitamin C.",
  },
  {
    id: 19,
    name: "Neutrophils — hypersegmented",
    association: "Slow maturation of neutrophils in bone marrow due to DNA synthesis impairment, pathological conditions.",
    recommendation: "Vitamin E, Vitamin A, Magnesium, Selenium, Zinc.",
  },
  {
    id: 20,
    name: "Neutrophils — nonviable/sluggish",
    association: "Impaired immune response.",
    recommendation: "Vitamin C, N-Acetylcysteine (NAC), Garlic, Beta Glucans, Turkey Tail Mushroom. Consider IV Vitamin C.",
  },
  {
    id: 21,
    name: "Neutrophils — cohesion (leukoagglutination)",
    association: "Chronic infection, autoimmune condition, liver and/or bowel toxicity.",
    recommendation: "B-Complex, Pantothenic Acid (B5), Vitamin D, Vitamin A, Vitamin E, Selenium, Milk Thistle, Glutathione, Gut Protocol.",
  },
  {
    id: 22,
    name: "Eosinophils (>4% of WBCs)",
    association: "Parasitic infection. If present with basophils, these often indicate an allergic/inflammatory response.",
    recommendation: "Quercetin, Elderberry, Olive Leaf Extract, Pau d'Arco, Anti-Parasitic Formulas.",
  },
  {
    id: 23,
    name: "Basophils (>1% of WBCs)",
    association: "Inflammation, allergic response, intestinal permeability.",
    recommendation: "Quercetin, High Dose Vitamin C, Zinc, L-Glutamine, Pantothenic Acid (B5).",
  },
  {
    id: 24,
    name: "Monocytes (size 'B' with kidney shaped nucleus)",
    association: "Chronic inflammation, viral disease, fungal disease, parasitic infection.",
    recommendation: "Quercetin, High Dose Vitamin C, Elderberry, Olive Leaf Extract, Pau d'Arco, Anti-Parasitic Formulas, Anti-Fungal Formulas, Caprylic Acid.",
  },
  {
    id: 25,
    name: "Lymphocytes (25–35% of WBCs)",
    association: "Viral infections. High numbers should be recorded with GP.",
    recommendation: "Vitamin C, Turkey Tail Mushroom Complex, N-Acetylcysteine (NAC), Garlic, Beta Glucans, Quercetin.",
  },
  {
    id: 26,
    name: "Symprotit",
    association: "Tissue pH imbalance, impaired oxygen transfer, increased toxicity stored in tissues.",
    recommendation: "Multi Nutrient, Spirulina, Greens supplement, Colloidal Minerals.",
  },
  {
    id: 27,
    name: "Macrosymprotit",
    association: "Chronic infection, immune impairment.",
    recommendation: "Mushroom Complex, Probiotic, Immune Regulating Herbals, Wild Oregano Oil.",
  },
  {
    id: 28,
    name: "Ascit forms / Synascit forms",
    association: "Degenerative conditions, mycosis/mould toxicity.",
    recommendation: "Probiotics, Wild Oregano Oil, Caprylic Acid, High Dose Vitamin C, Zinc, Beta Glucans, Anti-Candida Formulations, Bentonite Clay.",
  },
  {
    id: 29,
    name: "Acanthocytes (spur cells)",
    association: "Up to 3% considered OK. Neurological conditions, acquired disease states.",
    recommendation: "EFAs, Vitamin E, Vitamin D.",
  },
  {
    id: 30,
    name: "Echinocytes (burr cells)",
    association: "Antioxidant imbalance.",
    recommendation: "Antioxidant Formula, Colloidal Minerals, Vitamin C, Vitamin E, Vitamin D.",
  },
  {
    id: 31,
    name: "Poikilocytes (irregular/crushed)",
    association: "Antioxidant and electrolyte imbalances, chemical exposure, radiation exposure, oxidative stress on cells.",
    recommendation: "Antioxidant Formula, Colloidal Minerals, Vitamin C, Vitamin E, Multi Nutrient.",
  },
  {
    id: 32,
    name: "Stomatocytes",
    association: "Malabsorption, malnutrition, liver dysfunction.",
    recommendation: "N-Acetylcysteine (NAC), Glutathione, B-Complex, Pantothenic Acid (B5), Multi Nutrient.",
  },
  {
    id: 33,
    name: "Schistocytes (split cell)",
    association: "Oxidative stress, impaired liver function, haemoglobinuria, haemolytic anaemia, microangiopathic anaemia.",
    recommendation: "Adv. Digestive Enzyme taken on empty stomach (3x/day), Antioxidant Formula, Multi Nutrient, Vitamin E, Vitamin A.",
  },
  {
    id: 34,
    name: "Keratocytes (horn cell / bite cell)",
    association: "Disseminated intravascular coagulation, precipitated haemoglobin.",
    recommendation: "L-Carnitine, Vitamin E, EFAs, Vitamin A, N-Acetylcysteine (NAC), Antioxidant Formula.",
  },
  {
    id: 35,
    name: "Dacrocyte (tear drop cell)",
    association: "May be a marker of bone marrow fibrosis if numbers are increased.",
    recommendation: "Diindolylmethane (DIM), Lycopene, Boswellic Acid, Butyric Acid, Resveratrol, Selenium, Zinc, Quercetin, Vitamin D3.",
  },
  {
    id: 36,
    name: "Heinz bodies",
    association: "Denatured and precipitated haemoglobin, reduced energy.",
    recommendation: "N-Acetylcysteine (NAC), Vitamin C, Vitamin E, Vitamin A, EFAs.",
  },
  {
    id: 37,
    name: "Pteroharps (butterfly cells)",
    association: "Impaired sugar metabolism, respiratory illness, intestinal inflammation, Aspergillus infection.",
    recommendation: "Chromium Picolinate, Alpha Lipoic Acid, Probiotics, Berberine. Consider HOMA-IR.",
  },
  {
    id: 38,
    name: "Thallus",
    association: "Early development of fungal infection, tissue pH imbalance, Aspergillus infection.",
    recommendation: "Black Cumin (Black Seed) Oil, Black Walnut, Pau d'Arco, Caprylic Acid, Colloidal Silver, Wild Oregano Oil, Vitamin C.",
  },
  {
    id: 39,
    name: "Red crystals",
    association: "Bacterial overgrowth, bowel and/or liver toxicity, heavy metal load.",
    recommendation: "Heavy Metal Cleanse, Liver/Kidney Tonic.",
  },
  {
    id: 40,
    name: "Uric acid/oxalate crystals",
    association: "Gout, impaired kidney function.",
    recommendation: "Quercetin, Vitamin C, Folate, Propolis, Cherry Juice, Kidney Tonic.",
  },
  {
    id: 41,
    name: "Protoplast",
    association: "Compromised immune function, bacterial/fungal overgrowth, Aspergillus infection.",
    recommendation: "Pau d'Arco, Caprylic Acid, Bentonite Clay, Beta Glucans, Colloidal Silver.",
  },
  {
    id: 42,
    name: "RBC aggregation",
    association: "Poor circulation, low energy, muscle fatigue, increased toxicity.",
    recommendation: "Greens Product, Mineral Drops, Spirulina, Cayenne.",
  },
  {
    id: 43,
    name: "Plaque (<'A' bright white)",
    association: "Calcification, impaired sugar metabolism, impaired fat metabolism.",
    recommendation: "Berberine, L-Carnitine, Vitamin K, Astaxanthin, Artichoke Leaf, Lipotropic Factors. Consider HOMA-IR/Lipids Panel.",
  },
  {
    id: 44,
    name: "Triglyceride crystals",
    association: "Impaired sugar metabolism, impaired fat metabolism, marker for elevated cholesterol in higher amounts.",
    recommendation: "Berberine, L-Carnitine, Artichoke Leaf Extract, Lipotropic Factors, Niacin. Consider HOMA-IR/Lipids Panel.",
  },
  {
    id: 45,
    name: "Fermentation",
    association: "Carbohydrate metabolism impairment, often a first marker of perimenopause.",
    recommendation: "Digestive Enzymes at each meal, Chromium, Cinnamon, Alpha Lipoic Acid, Berberine. Consider HOMA-IR.",
  },
  {
    id: 46,
    name: "Fibrothallus",
    association: "Joint pain/inflammation.",
    recommendation: "Joint Formula, Hyaluronic Acid, MSM, B-Complex, Vitamin C, Enzymes on empty stomach.",
  },
  {
    id: 47,
    name: "Advanced polymorphs",
    association: "Pre-degenerative stage, long-term pH imbalance.",
    recommendation: "Antioxidant Complex, Spirulina, Chlorella, Bicarbonate, Support Detox pathways.",
  },
  {
    id: 48,
    name: "Thrombocyte aggregation",
    association: "Low energy, fatigue, cellular oxygenation issues, brain fog, increased inflammation.",
    recommendation: "Magnesium, Trace Minerals.",
  },
  {
    id: 49,
    name: "Mineralisation",
    association: "Calcification of cardiovascular system, bone density issues, hypertension.",
    recommendation: "Vitamin K, Vitamin D3, Mineral Complex, Concentrated Mineral Drops.",
  },
  {
    id: 50,
    name: "Parasite/bacterial bodies",
    association: "Low energy, digestive impairment, compromised immunity, headache, skin issues.",
    recommendation: "Black Cumin (Black Seed) Oil, Black Walnut, Pau d'Arco, Caprylic Acid, Colloidal Silver, Wild Oregano Oil, Cayenne, Increased Fibre.",
  },
  {
    id: 51,
    name: "Hydrogels",
    association: "",
    recommendation: "",
  },
  {
    id: 52,
    name: "Symplasts",
    association: "",
    recommendation: "",
  },
];